'use client';
import { useState } from 'react';
import Image from 'next/image';
import { PageShell } from '@/components/PageShell';

const times = ['08:00','10:00','12:00','14:00','16:00'];
const courts = Array.from({length:8},(_,i)=>`CRT 0${i+1}`);
const taken = new Set(['0-0','1-1','2-4','3-0','3-2','4-0','4-3','5-0','5-3','6-0','6-4','7-0','7-2']);

export default function BookingPage(){const [slot,setSlot]=useState('0-3'); const [court,setCourt]=useState('Court - 1'); return <PageShell><main><section className="py-24 md:py-36"><div className="container-page"><h1 className="display-title text-left">Reserve Your Line</h1></div></section><section className="pb-24"><div className="container-page grid gap-12 lg:grid-cols-[1fr_360px]"><div><div className="mb-12 grid gap-8 md:grid-cols-2"><label className="brand-card p-8"><span className="eyebrow mb-5 block">Select Court</span><select className="w-full border border-brand/25 bg-white p-4 text-xl uppercase" value={court} onChange={e=>setCourt(e.target.value)}>{[1,2,3,4].map(n=><option key={n}>Court - {n}</option>)}</select></label><label className="brand-card p-8"><span className="eyebrow mb-5 block">Booking Date</span><input className="w-full border border-brand/25 bg-white p-4 text-xl" value="October 24, 2026" readOnly /></label></div><div className="mb-8 flex items-center justify-between"><h2 className="text-3xl uppercase tracking-[0.22em]">Court Availability</h2><div className="hidden gap-5 text-xs uppercase tracking-nav text-ink/50 sm:flex"><span>■ Taken</span><span className="text-brand">■ Selected</span><span>□ Open</span></div></div><div className="overflow-x-auto border border-brand/25 bg-white"><table className="w-full min-w-[700px] border-collapse"><thead><tr className="bg-paper text-xs uppercase tracking-nav text-ink/50"><th className="p-5 text-left">Court</th>{times.map(t=><th key={t} className="p-5 text-center">{t}</th>)}</tr></thead><tbody>{courts.map((c,ri)=><tr key={c} className="border-t border-brand/10"><td className="p-5 text-brand">{c}</td>{times.map((t,ti)=>{const id=`${ri}-${ti}`; const isTaken=taken.has(id); const selected=slot===id; return <td className="p-3" key={id}><button disabled={isTaken} onClick={()=>setSlot(id)} className={`h-14 w-full border ${selected?'border-brand bg-brand text-white':isTaken?'border-slate-200 bg-slate-200 text-slate-400':'border-brand/15 bg-white'}`}>{isTaken?'×':''}</button></td>})}</tr>)}</tbody></table></div></div><aside><div className="brand-card p-10"><h2 className="mb-16 text-3xl uppercase tracking-[0.22em]">Your Booking</h2><p className="eyebrow mb-3">Session</p><p className="mb-10 text-lg uppercase tracking-[0.18em]">Court 01 · Indoor Pro</p><p className="eyebrow mb-3">Schedule</p><p className="mb-10 text-lg uppercase tracking-[0.18em]">Oct 26 | 14:00 - 16:00</p><p className="eyebrow mb-3">Member Discount</p><p className="mb-12 text-4xl">$45.00</p><button className="brand-btn primary w-full">Proceed With Payment</button><p className="mt-8 text-center text-xs uppercase leading-6 tracking-nav text-ink/45">24h cancellation policy applies. No refunds for no-shows.</p></div><Image src="/images/racket-shuttle.jpg" alt="Feather Fitness" width={800} height={420} className="mt-10 aspect-[2/1] w-full object-cover"/></aside></div></section></main></PageShell>}
