import Image from 'next/image';
import { PageShell } from '@/components/PageShell';
import { Hero } from '@/components/Hero';
import { CTA } from '@/components/CTA';

const benefits = ['Priority Access','Recovery Suite','Private Events'];
const tiers = [
  { name:'Club', price:'$180', items:['7-day advance booking','Lounge access','Member social sessions'] },
  { name:'Elite', price:'$320', items:['14-day advance booking','Unlimited recovery access','Monthly guest passes','Quarterly AI analysis'], featured:true },
  { name:'Pro', price:'$550', items:['Permanent court booking','Personal locker & valet','Master stringing service','Dedicated performance coach'] }
];

export default function MembershipPage(){return <PageShell><main><Hero eyebrow="Beyond the court" title="Membership">An ecosystem of athletic excellence. Access private lounges, world-class recoveries, and a community defined by precision and velocity.</Hero><section className="bg-white py-24"><div className="container-page"><div className="mb-16 grid gap-8 md:grid-cols-2"><h2 className="section-title">The Curated Experience</h2><p className="body-copy md:text-right">Reserved for those who seek more than performance—membership is an entry into a lifestyle of quiet confidence.</p></div><div className="grid gap-8 md:grid-cols-3">{benefits.map((b)=><article className="brand-card p-10" key={b}><p className="mb-8 text-3xl text-brand">⌁</p><h3 className="mb-5 text-xl uppercase tracking-[0.2em]">{b}</h3><p className="body-copy">Exclusive membership experiences designed around comfort, precision and performance.</p></article>)}</div></div></section><section className="bg-mist py-24"><div className="container-page grid items-center gap-16 lg:grid-cols-2"><Image src="/images/racket-shuttle.jpg" alt="Racket detail" width={1000} height={560} className="aspect-[4/3] w-full object-cover"/><div><p className="eyebrow mb-5">Engineered Edge</p><h2 className="section-title mb-10">Performance Optimization</h2><p className="body-copy mb-8">Biometric tracking and court analysis powered by AI, available for all Elite and Pro tier members.</p><p className="body-copy border-t border-brand/25 pt-8">Personal lockers, complimentary valet, and a dedicated concierge for all athletic and scheduling needs.</p></div></div></section><section className="py-24 text-center"><h2 className="section-title mb-5">The Tiers</h2><p className="body-copy mx-auto mb-14 max-w-xl">Select the level of engagement that aligns with your pursuit of excellence.</p><div className="container-page grid gap-8 md:grid-cols-3">{tiers.map((t)=><article className={`brand-card p-10 text-left ${t.featured?'border-2 border-brand shadow-soft':''}`} key={t.name}><p className="eyebrow mb-4">{t.name}</p><p className="mb-8 text-4xl">{t.price}<span className="text-sm text-ink/45"> /mo</span></p><ul className="mb-10 space-y-5 text-sm text-ink/70">{t.items.map(i=><li key={i}>✓ {i}</li>)}</ul><button className={`brand-btn w-full ${t.featured?'primary':''}`}>Select {t.name}</button></article>)}</div></section><section className="bg-mist py-24 text-center"><h2 className="section-title mb-14">Member Feedbacks</h2><div className="container-page grid gap-8 md:grid-cols-3">{['Quynh','Michael','Yao'].map(n=><article className="brand-card p-10 text-left" key={n}><p className="eyebrow mb-6">Member</p><h3 className="mb-5 text-xl uppercase tracking-[0.2em]">{n}</h3><p className="body-copy">The facilities are outstanding, the courts feel premium, and every session feels professionally managed.</p></article>)}</div></section><CTA /></main></PageShell>}
